version: '3'
services:
    sqlite3:
        image: nouchka/sqlite3:latest
        stdin_open: true
        tty: true
        volumes:
            - ./db/:/root/db/
    web:
        build: .
        ports:
            - "8000:8000"
        image: lissa00/sqr:latest
        volumes:
            - .:/app
            - ./db/:/app/db/
