name: CI

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Decrypt GPG file
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_KEY }}" --output serviceAccountKey.json serviceAccountKey.json.gpg

      - name: Test
        run: |
          export USER_TEST=${{secrets.DB_USER_TEST}}
          export PASSWORD_TEST=${{secrets.DB_PASSWORD_TEST}}
          export HOST_TEST=${{secrets.DB_HOST_TEST}}
          export DB_PORT_TEST=${{secrets.DB_PORT_TEST}}
          export DB_NAME_TEST=${{secrets.DB_NAME_TEST}}
          export TEST_USER_EMAIL=${{secrets.TEST_USER_EMAIL}}
          export TEST_USER_PASSWORD=${{secrets.TEST_USER_PASSWORD}}
          export TEST_URL=${{secrets.TEST_URL}}
          pip install -r requirements.txt
          pip install pytest
          pip install pytest-cov
          pytest --cov=. test/

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Decrypt GPG file
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_KEY }}" --output serviceAccountKey.json serviceAccountKey.json.gpg

      - name: Login to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
          
      - name: Export database info
        run: |
          heroku config:set USER=${{secrets.DB_USER}} -a ${{secrets.HEROKU_APP_NAME}}
          heroku config:set PASSWORD=${{secrets.DB_PASSWORD}} -a ${{secrets.HEROKU_APP_NAME}}
          heroku config:set HOST=${{secrets.DB_HOST}} -a ${{secrets.HEROKU_APP_NAME}}
          heroku config:set DB_PORT=${{secrets.DB_PORT}} -a ${{secrets.HEROKU_APP_NAME}}
          heroku config:set DB_NAME=${{secrets.DB_NAME}} -a ${{secrets.HEROKU_APP_NAME}}

      - name: Push to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
